CREATE FUNCTION FROMPERSON ()
     RETURNS ROW (NAME VARCHAR(10), FIRSTNAME VARCHAR(10))
     LANGUAGE SQL
     CONTAINS SQL
     NO EXTERNAL ACTION
     DETERMINISTIC
     RETURN VALUES ('', '')
     
     DROP FUNCTION FROMPERSON