

INSERT INTO SYNC_DATABASE_INFORMATION(DATABASE_INFORMATION_ID, DB_DRIVER, DB_URL, DB_USER, DB_PASSWORD, IS_ACTIVE) 
VALUES(
	(1),
	('com.ibm.db2.jcc.DB2Driver'), 
	('jdbc:db2://192.168.105.25:50001/champ'), 
	('db2inst1'), 
	('db2inst1'),
	(1)
);

INSERT INTO SYNC_DATABASE_INFORMATION(DATABASE_INFORMATION_ID, DB_DRIVER, DB_URL, DB_USER, DB_PASSWORD, IS_ACTIVE) 
VALUES(
	(2),
	('com.ibm.db2.jcc.DB2Driver'), 
	('jdbc:db2://192.168.105.25:50002/champ'), 
	('db2inst1'), 
	('db2inst1'),
	(1)
);

INSERT INTO SYNC_SQL_SYNC_STATUS VALUES(
	1,
	'ยังไม่ได้ดำเนินการ'
);

INSERT INTO SYNC_SQL_SYNC_STATUS VALUES(
	2,
	'ดำเนินการแล้ว'
);

INSERT INTO SYNC_SQL_SYNC_STATUS VALUES(
	3,
	'ดำเนินการ'
);

INSERT INTO SYNC_TABLE VALUES(
	'CHAMPINFO'
);

INSERT INTO SYNC_DESCRIPTION VALUES(
	'INSERT_CHAMPINFO',
	'CHAMPINFO TABLE DESCRIPTION ON INSERT EVENT'
);

INSERT INTO SYNC_DESCRIPTION VALUES(
	'UPDATE_CHAMPINFO',
	'CHAMPINFO TABLE DESCRIPTION ON UPDATE EVENT'
);

INSERT INTO SYNC_DESCRIPTION VALUES(
	'DELETE_CHAMPINFO',
	'CHAMPINFO TABLE DESCRIPTION ON DELETE EVENT'
);
