CREATE OR REPLACE PROCEDURE INSERT_SYNC_INFORMATION(DESCRIPTION VARCHAR(100), SQL_MARKED_RECEIVED VARCHAR(100), SQL_STATEMENT VARCHAR(500))
  LANGUAGE SQL
  BEGIN ATOMIC
  	DECLARE NEW_SYNC_INFORMATION_ID INTEGER;
    FOR v AS cur1 CURSOR FOR 
                SELECT DATABASE_INFORMATION_ID FROM SYNC_DATABASE_INFORMATION WHERE IS_ACTIVE = 1
    DO 
      SET NEW_SYNC_INFORMATION_ID = (SELECT CASE WHEN MAX(SYNC_INFORMATION_ID) IS NULL THEN 1 ELSE MAX(SYNC_INFORMATION_ID) + 1 END FROM SYNC_INFORMATION);
      INSERT INTO SYNC_INFORMATION(SYNC_INFORMATION_ID, DESCRIPTION, SQL_STATEMENT, SQL_MARKED_RECEIVED, SQL_SYNC_STATUS_ID, DATABASE_INFORMATION_ID, CREATE_TIME, SYNC_TIME) VALUES(
     		NEW_SYNC_INFORMATION_ID,
     		DESCRIPTION,
     		SQL_STATEMENT,
     		SQL_MARKED_RECEIVED,
     		1,
     		v.DATABASE_INFORMATION_ID,
     		CURRENT_TIMESTAMP,
     		NULL
     	);
    END FOR;
  END
  
  