-- Tables
CREATE TABLE DATABASE_INFORMATION(
DB_DRIVER VARCHAR(100) FOR BIT DATA,
DB_URL VARCHAR(100) FOR BIT DATA,
DB_USER VARCHAR(100) FOR BIT DATA,
DB_PASSWORD VARCHAR(100) FOR BIT DATA
);

CREATE TABLE SQL_SYNC_STATUS(
SQL_SYNC_STATUS_ID SMALLINT NOT NULL,
SQL_SYNC_STATUS_DETAIL VARCHAR(100),
PRIMARY KEY(SQL_SYNC_STATUS_ID)
);

CREATE TABLE SYNCHRONIZE_INFORMATION(
SYNCHRONIZE_INFORMATION_ID INTEGER NOT NULL,
SQL_LIST CLOB,
SQL_DESCRIPTION VARCHAR(150),
SQL_SYNC_STATUS_ID SMALLINT,
PRIMARY KEY(SYNCHRONIZE_INFORMATION_ID),
FOREIGN KEY (SQL_SYNC_STATUS_ID) REFERENCES SQL_SYNC_STATUS(SQL_SYNC_STATUS_ID)
);

-- SET DATABASE ENCRYPTION PASSWORD
SET ENCRYPTION PASSWORD = 'asdqwe123';

INSERT INTO DATABASE_INFORMATION(DB_DRIVER, DB_URL, DB_USER, DB_PASSWORD) 
VALUES(
	ENCRYPT('com.ibm.db2.jcc.DB2Driver'), 
	ENCRYPT('jdbc:db2://192.168.105.25:50000/champ'), 
	ENCRYPT('db2inst1'), 
	ENCRYPT('db2inst1')
);

INSERT INTO DATABASE_INFORMATION(DB_DRIVER, DB_URL, DB_USER, DB_PASSWORD) 
VALUES(
	ENCRYPT('com.ibm.db2.jcc.DB2Driver'), 
	ENCRYPT('jdbc:db2://192.168.105.25:50001/champ'), 
	ENCRYPT('db2inst1'), 
	ENCRYPT('db2inst1')
);

INSERT INTO SQL_SYNC_STATUS VALUES(
	1,
	'ยังไม่ได้ดำเนินการ'
);

INSERT INTO SQL_SYNC_STATUS VALUES(
	2,
	'ดำเนินการแล้ว'
);

--SELECT 
--	DECRYPT_CHAR(DB_DRIVER),
--	DECRYPT_CHAR(DB_URL),
--	DECRYPT_CHAR(DB_USER),
--	DECRYPT_CHAR(DB_PASSWORD) 
--FROM DATABASE_INFORMATION;
