-- QUERY ALL TRIGGERS IN DBMS => SELECT * FROM SYSCAT.TRIGGERS

CREATE TRIGGER SYNC_CHAMPINFO_AFTER_INSERT_TRIGGER
     AFTER INSERT ON CHAMPINFO
     REFERENCING NEW AS NEW
     FOR EACH ROW
     BEGIN ATOMIC
     	DECLARE DESCRIPTION VARCHAR(100);
     	DECLARE SQL_STATEMENT VARCHAR(500);
     	DECLARE SQL_MARKED_RECEIVED VARCHAR(500);
     	DECLARE IS_CONTINUE SMALLINT;
     	SET IS_CONTINUE = (SELECT CASE WHEN COUNT(*) = 0 THEN 1 ELSE 0 END AS IS_CONTINUE FROM SYNC_MARKED_RECEIVED_DATA WHERE TABLENAME = 'CHAMPINFO' AND ID_OF_TABLE = NEW.CHAMP_ID);
     	IF IS_CONTINUE = 1 THEN
     		SET DESCRIPTION = (SELECT DESCRIPTION FROM SYNC_DESCRIPTION WHERE EVENT_TABLENAME = 'INSERT_CHAMPINFO');
	     	SET SQL_STATEMENT = (
	     		'INSERT INTO CHAMPINFO(CHAMP_ID, CHAMP_DETAIL) VALUES(''' 
	     		CONCAT NEW.CHAMP_ID 
	     		CONCAT ''', ''' 
	     		CONCAT NEW.CHAMP_DETAIL 
	 			CONCAT ''')'
	 		);
	 		SET SQL_MARKED_RECEIVED = (
	 			'INSERT INTO SYNC_MARKED_RECEIVED_DATA(TABLENAME, ID_OF_TABLE) VALUES('''
	 			CONCAT 'CHAMPINFO'
	 			CONCAT ''','''
	 			CONCAT NEW.CHAMP_ID
	 			CONCAT ''')'
	 		);
	     	
	     	CALL INSERT_SYNC_INFORMATION(DESCRIPTION, SQL_MARKED_RECEIVED, SQL_STATEMENT);
	    ELSE
	    	DELETE SYNC_MARKED_RECEIVED_DATA WHERE TABLENAME = 'CHAMPINFO' AND ID_OF_TABLE = NEW.CHAMP_ID;
     	END IF;
     END